ITensor/ITensor

- itensor/global.h
- itensor/mps/mpo.h
- itensor/real.h
Static in namespace scope is superfluous. So I change "static const" to "const" in 
* global.h
* mpo.h
* real.h
> change static const in namespace scope to const

- CMakeLists.txt
- utilities/cputime.cc
I confirmed , with these changes ITensor can be compiled with cmake + MSVC + MKL using the following command
```
cmake.exe E:\dev\src\ITensor -G "Visual Studio 12 2013 Win64" -DSample=OFF -DTutorial=OFF -DTesting=OFF -DBLA_VENDOR=Intel
```
> Changes for MSVC compatibility

- itensor/indexset.h
There exists an const error in the IndexSetIter::operator+(), which affect the following codes.
` Index s1=Index("s1",4),s2=Index("s2",6);
auto b=delta(s1,s2);
auto c=b.inds().begin();
PrintData(*c);
PrintData(*(c+1));`
where the += operator in the diffinition of operaotr+() actually modifies the value of x.
The IndexSetIter::operator-() may also occurs this const error, but I haven't test it.
> fix a const error in IndexSetIter::operator+()

- itensor/decomp.cc
- itensor/detail/skip_iterator.h
- itensor/tensor/contract.cc
- itensor/tensor/range.h
size of unsigned long does not match size of itensor::Index for LLP64 systems like Windows, resulting in static_cast errors. Use size_t instead.
> Use size_t instead of unsigned long.

- options.mk.sample
By default OpenBLAS uses C99 complex type in complex.h, which defines I. This definition conflicts with the use of I as template parameters in range.h. Defining the two macros as in the sample circumvents this problem.
> Updates to options.mk.sample for OpenBLAS

- itensor/util/error.h
abort() is declared in cstdlib.
> Fixed error.h to #include <cstdlib>

- itensor/mps/sweeps.h
Minor change of the file sweeps.h. Now if the number of row of sweep parameters in the input file is less than nsweep, the last row will repeat.
> Minor change of the file sweeps.h

- itensor/mps/lattice/square.h
- itensor/mps/lattice/triangular.h
Corrected lattice bonds generation for 1D chains and ladders.
Previously extra bonds were added for periodic boundary conditions and Ny<=2
> Lattice generation

- itensor/itensor_operators.cc
- itensor/mps/sites/hubbard.h
Found a typo in the detail::checkArrow function and fixed it. Now it prints the correct IndexSet to the console when IQIndices do not have matching arrows. Before, it was giving the same IndexSet twice.
> Fixed typo in detail::checkArrows

- itensor/itdata/qcombiner.cc
- itensor/itdata/qcombiner.h
- itensor/mps/sweeps.h
Hi, 
I was able to fix the problem I was describing here: http://itensor.org/support/489/segmentation-fault-when-using-combiner
I implemented the necessary read/write methods and now it works. I tried to be as consistent with your style as possible. I hope you can merge it into your repository. 
I also fixed another problem with the read/write of Sweeps. 
If you have questions or comments, just let me know. 
Best,
Lars
> Fixes Sweeps Bug and Implemented Read/Write for QCombine

- itensor/util/error.h
to avoid name conflicts to other libraries such as boost
> enclose error funcs in itensor namespace

- itensor/itensor_interface.h
- itensor/itensor_interface.ih
- itensor/itensor_operators.cc
- unittest/iqtensor_test.cc
- unittest/itensor_test.cc
Fixes order so that it works properly when a default-constructed ITensor is input.
> order: fix for default-constructed input ITensor

- itensor/indexset.h
- itensor/indexset.ih
- itensor/itensor_interface.h
- itensor/itensor_interface.ih
- itensor/itensor_operators.cc
- unittest/indexset_test.cc
- unittest/iqtensor_test.cc
- unittest/itensor_test.cc
Adds primeLevel function for IndexSets and ITensors so that the prime levels of ITensors can be directly specified given the index ordering (closes #143).
> order: primeLevel for IndexSet and ITensor

- itensor/itensor_interface.h
- itensor/itensor_interface.ih
- itensor/itensor_operators.cc
- unittest/iqtensor_test.cc
- unittest/itensor_test.cc
I noticed with the following type of code:
```
Index i("i",2), j("j",2);
auto A = randomTensor(i,j);
for(auto s : range1(i.m())) A.set(s,s,sqrt(A.real(s,s)));
```
the new .set, .cplx, etc. aren't dispatching correctly, since the new versions were limited to just accepting `int`'s while `s` above becomes type `long int`, so it tries to use the versions that are meant for `IndexVal`'s and throws an error. I extended .cplx and .set to accept anything that is convertible to an `int`, let me know if this seems like the way to go.
> Extend .set to work with long int

- itensor/indexset.ih
- itensor/qn.h
- `indexset.ih`
Return an empty local `static const IndexT` instance instead of creating one every time. This fixes warnings since `findtype` and `finddir` both return lvalue references.
- `qn.h`
Defined unary minus for `const QNVal`
> Minor fixes

- itensor/itensor_interface.ih
`itensor::TooSmallForReal` is derived from `std::runtime_error`.  This is a
polymorphic type, so cathing it by value is dangerous.  gcc 8 warns about
this:
[...]/itensor/itensor/itensor_interface.ih:220:5: warning:
catching polymorphic type ‘class itensor::TooSmallForReal’ by value
catch(TooSmallForReal)
^~~~~
This fixes this bug.
> Fix catching polymorphic `TooSmallForReal` by value

- itensor/mps/mpo.h
- itensor/mps/mpoalgs.cc
- unittest/mpo_test.cc
1. I added an extra applyMPO method where a user can input a starting guess for the output wavefunction (as we discussed, this only works for "Fit" and throws an error for "DensityMatrix". Also, the guess wavefunction is not overwritten)
2. The "DensityMatrix" method did not have an option to normalize the output wavefunction, so I added that for consistency with the "Fit" method
3. I changed the default of applyMPO to not normalize the output wavefunction
> Add applyMPO method which allows for a starting guess wavefunction

- itensor/mps/mpoalgs.cc
If you don't do this, the "last" bond in the resulting MPO can have way (WAY) higher bond dimension than all others. Now, the svdBond respects the "global" Maxm.
> Have final svdBond respect args in nmultMPO

- itensor/mps/mpo.cc
- itensor/mps/mpo.h
- unittest/mpo_test.cc
As discussed in #185, here is a more complete implementation of the MPO error function. Note that the `abs` in line 573 is necessary due to underflow when normalization is large.
> New function errorMPOProd

- itensor/itensor_interface.h
- itensor/itensor_interface_impl.h
- unittest/iqtensor_test.cc
- unittest/itensor_test.cc
This makes them consistent with .set(), which can take vector<IndexVal>, etc. This was suggested by Andreas on the ITensor support page.
> .real() and .cplx() can take vector<IndexVal> and vector<int>

- itensor/decomp.cc
- itensor/hermitian.cc
- itensor/mps/dmrg.h
- itensor/svd.cc
- unittest/decomp_test.cc
This adds an argument "IgnoreDegeneracy" to the functions svd(), diagHermitian(), and dmrg() which allows a user to specify whether or not degeneracies in the singular value spectrum or eigenvalue spectrum are ignored when truncating.
In this pull request, "IgnoreDegeneracy" defaults to true for svd() and diagHermitian(), and defaults to false for dmrg().
I am definitely open to suggestions about the name of the flag and the defaults. With these defaults, it makes it so that simple situations like:
```c++
auto i = IQIndex("i",Index("i",2),QN(0));
auto A = IQTensor(i,dag(prime(i)));
A.set(1,1,1.0);
A.set(2,2,1.0);
IQTensor U(i),S,V;
svd(A,U,S,V,{"Maxm=",1});
```
"just work" now, i.e. truncates one of the singular values and outputs potentially random singular vectors. This case currently …
> Add IgnoreDegeneracy flag to svd, diagHermitian, and dmrg

- itensor/decomp.h
- itensor/mps/autompo.cc
- itensor/mps/mpoalgs.cc
- itensor/mps/mps.cc
- itensor/mps/mps.h
- itensor/mps/mps_impl.h
- itensor/qn.cc
- unittest/mpo_test.cc
- unittest/mps_test.cc
I have tried to make the tag conventions a bit more sane for MPS and MPO.
Both now have the conventions that the sites have tags "Site,n=#", and links have conventions "Link,l=#". I added tests to check that some basic MPS and MPO operations like gauging, adding, applyMPO, etc respect the tag convention. 
I think I have missed some spots, and it would be nice to have a good way for users to specify their own convention, but I think this is a good start.
> Tag convention for MPS and MPO, with tests

- itensor/index.h
- itensor/indexset.h
- itensor/itensor_interface.h
- itensor/mps/DMRGObserver.h
- itensor/mps/autompo.cc
- itensor/mps/dmrg.h
- Fixed a small bug, in which the "verbose" option on DMRG worked for IQMPOs but not for MPOs.
- Added an extra setting, "Silent", which implies Quiet and also suppresses all other outputs. (This is desirable if DMRG is used as a sub-routine on an algorithm.)
> Silent DMRG

- itensor/indextype.h
using the stl algorithm instead of a for loop, arguably improves readability and produced significantly less assembly for gcc 8.3.0 and clang 8.0.0 with -O3
> suggested minor improvements to indextype
